server:
  port: 8081

spring:
  application:
    name: sse-mcp-server-demo2
  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: mcp-server
        version: 1.0.0
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-endpoint: /sse
        sse-message-endpoint: /mcp
        type: sync

  logging:
    level:
      io.modelcontextprotocol: TRACE
      org.springframework.ai.mcp: TRACE
